"""Initial migration

Revision ID: 9ae2a0770b6c
Revises: 
Create Date: 2026-03-25 21:56:23.973162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ae2a0770b6c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.add_column('channels', sa.Column('org_id', sa.Integer(), nullable=True))
    op.add_column('channels', sa.Column('name_en', sa.String(length=100), nullable=True))
    op.add_column('channels', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('channels', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('channels', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_channels_channel_id', table_name='channels')
    op.create_index('ix_channel_platform_active', 'channels', ['platform', 'is_active'], unique=False)
    op.create_unique_constraint(None, 'channels', ['channel_id'])
    op.create_foreign_key(None, 'channels', 'organizations', ['org_id'], ['id'])
    op.add_column('streams', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('streams', sa.Column('peak_viewers', sa.Integer(), nullable=True))
    op.add_column('streams', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    op.add_column('streams', sa.Column('ended_at', sa.DateTime(), nullable=True))
    op.add_column('streams', sa.Column('duration_secs', sa.Integer(), nullable=True))
    op.add_column('streams', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index('ix_stream_channel_status', 'streams', ['channel_id', 'status'], unique=False)
    op.create_index('ix_stream_status_platform', 'streams', ['status', 'platform'], unique=False)
    op.create_index(op.f('ix_streams_status'), 'streams', ['status'], unique=False)
    op.create_index(op.f('ix_streams_video_id'), 'streams', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_streams_video_id'), table_name='streams')
    op.drop_index(op.f('ix_streams_status'), table_name='streams')
    op.drop_index('ix_stream_status_platform', table_name='streams')
    op.drop_index('ix_stream_channel_status', table_name='streams')
    op.drop_column('streams', 'created_at')
    op.drop_column('streams', 'duration_secs')
    op.drop_column('streams', 'ended_at')
    op.drop_column('streams', 'scheduled_at')
    op.drop_column('streams', 'peak_viewers')
    op.drop_column('streams', 'description')
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.drop_constraint(None, 'channels', type_='unique')
    op.drop_index('ix_channel_platform_active', table_name='channels')
    op.create_index('ix_channels_channel_id', 'channels', ['channel_id'], unique=1)
    op.drop_column('channels', 'updated_at')
    op.drop_column('channels', 'created_at')
    op.drop_column('channels', 'is_active')
    op.drop_column('channels', 'name_en')
    op.drop_column('channels', 'org_id')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
