"""add unique constraint to streams

Revision ID: c67d89f3ec8e
Revises: add_bilibili_user_creds
Create Date: 2026-04-07 01:36:37.513841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c67d89f3ec8e'
down_revision: Union[str, None] = 'add_bilibili_user_creds'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blacklisted_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blacklisted_tokens_id'))
        batch_op.drop_index(batch_op.f('ix_blacklisted_tokens_jti'))

    op.drop_table('blacklisted_tokens')
    with op.batch_alter_table('streams', schema=None) as batch_op:
        batch_op.alter_column('video_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.create_unique_constraint('uix_stream_channel_video', ['channel_id', 'video_id'])

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.alter_column('like_count',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.alter_column('like_count',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('streams', schema=None) as batch_op:
        batch_op.drop_constraint('uix_stream_channel_video', type_='unique')
        batch_op.alter_column('video_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    op.create_table('blacklisted_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('jti', sa.VARCHAR(length=64), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('expired_at', sa.DATETIME(), nullable=False),
    sa.Column('revoked_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blacklisted_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blacklisted_tokens_jti'), ['jti'], unique=1)
        batch_op.create_index(batch_op.f('ix_blacklisted_tokens_id'), ['id'], unique=False)

    # ### end Alembic commands ###
