"""add_shape_fields_and_indexes

Revision ID: c8b4874c0bce
Revises: dfc9fd02835d
Create Date: 2026-03-28 15:32:05.243029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8b4874c0bce'
down_revision: Union[str, None] = 'dfc9fd02835d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_shape', sa.String(length=10), nullable=True))

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_shape', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('logo_shape')

    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_column('avatar_shape')

    # ### end Alembic commands ###
