"""add danmakus table

Revision ID: dfc9fd02835d
Revises: 9ae2a0770b6c
Create Date: 2026-03-28 01:09:02.161669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfc9fd02835d'
down_revision: Union[str, None] = '9ae2a0770b6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('danmakus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=100), nullable=False),
    sa.Column('messages', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('danmakus', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_danmakus_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_danmakus_stream_id'), ['stream_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('danmakus', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_danmakus_stream_id'))
        batch_op.drop_index(batch_op.f('ix_danmakus_id'))

    op.drop_table('danmakus')
    # ### end Alembic commands ###
